### ISSUE TITLE
GPL, Trademarks & related files

### ISSUE THREAD

**Issue by ClassicPress** [ClassicPress/ClassicPress_Deprecated#1]
Let's kick off the project in the right way with a clear statement that we will adhere to the GPL license for WordPress. This ticket will initially track the discussion on how we will make the project GPL compliant and the steps we need to take.

We also want to outline that we will make sure that we adhere to WordPress trademarks. Details can be found here: https://wordpressfoundation.org/trademark-policy/

I think it's fair to say WordPress will probably be against this fork, so we need to make sure we remove all trademarked and copyrighted material from the project as our first major priority.

Please leave comments and suggestions about anything we should be aware of for this process.

**Comment by hlashbrooke** [comment]
> I think it's fair to say WordPress will probably be against this fork, so we need to make sure we remove all trademarked and copyrighted material from the project as our first major priority.

Just to mention that "WordPress" (whoever you define that as) will not be against this at all - this kind of fork is entirely in the spirit of the GPL and open-source. While ClassicPress won't be supported as an officially maintained WordPress.org project of course, there's no reason why anyone involved in WordPress will be against it.

And you will definitely need to remove any trademarked and copyright material, but that's purely a legal thing and not because of any issue that anyone will have with ClassicPress.

My point is that I'm just clearing up the fact that this kind of fork is totally fine and entirely within the spirit of the GPL, so I'd strongly recommend against starting off the project with an "us vs them" mentality as that just kicks things off with anger and a bitter sentiment, which is not a healthy way for any project to start.  You did after all say "Let's kick off the project in the right way" :)

**Comment by scottybo** [comment]
Closed and move to: https://github.com/ClassicPress/ClassicPress-v1/issues/265
