### ISSUE TITLE
IMPORTANT: Please read first

### ISSUE THREAD

**Issue by scottybo** [ClassicPress/ClassicPress_Deprecated#11]
After advice we will be forking https://github.com/WordPress/wordpress-develop as this contains all the PHP Unit tests (among other things).

PLEASE DON'T work on this repository just yet as we will most likely be removing/replacing it in the very near future.

**Comment by senlin** [comment]
Thanks for the head's up.

Not sure if this is the right place, but don't want to open it as an issue.
How to get started with helping you to pull this off? I am willing to dedicate a good chunk of my time to this project and I think it will be good to keep the momentum.

Is there anything we can do at this moment or in the not too distant future?

There was a comment over at WP Tavern where the poster said that while at it, WP good get cleaned up a lot further: https://wptavern.com/classicpress-gutenberg-not-included#comment-256952

Someone else suggested that the name ClassicPress is likely to cause trouble as it is an [existing theme](https://wptavern.com/classicpress-gutenberg-not-included#comment-257168)?

And to be honest, if this really is becoming something, then I expect you (the project) can expect to receive a lot of pushback from Matt and friends, including legal action. They have done it before and they won't shy away from abusing their power again.

This would mean that before publishing anything other than plans, we need to make sure to rip out anything proprietary to WP. That in itself is probably already a monster job :)

**Comment by hlashbrooke** [comment]
> And to be honest, if this really is becoming something, then I expect you (the project) can expect to receive a lot of pushback from Matt and friends, including legal action. They have done it before and they won't shy away from abusing their power again.

As I said in #1 - this kind of project is exactly what the GPL was designed for, so there will be zero pushback (and certainly no legal action) from any official channels. After all, this is just how WordPress itself was started - as a fork of an existing platform. If you misuse the WordPress trademark or the GPL in any way, then yeah, that would be a legal issue, but that would go without saying for any project, regardless of what it is or how/why it's being forked.

I don't know what you mean by "they have done it before" because there is no precedent for this, so would be very interested to know what you're referring to there :)

**Comment by senlin** [comment]
With "they have done it before" I meant abusing their power. I remember not too long ago that Matt bought a domain with foundation money to "just show who's boss" and then a lot longer ago there was the GPL debacle. There actually have been quite a few matters.
EDIT: anyone remembers Thesis?

I agree with you that this is what GPL was designed for. 

I'm just saying that, GPL or not, I expect pushback and only the future will tell...

**Comment by hlashbrooke** [comment]
The situation you are referring to was one where the GPL was being misused and abused, so "pushback" was indeed warranted and legally correct with no "abuse of power".

> I'm just saying that, GPL or not, I expect pushback and only the future will tell...

As far as I can tell, ClassicPress has so far been doing things the right way and I am sure that @scottybo will continue with respecting the GPL and the WordPress trademark. If that does indeed continue, then no pushback or will be necessary or even legal.

I would strongly caution anyone working on ClassicPress from seeing it as a "ClassicPress vs WordPress" thing, as that will make this a project based on picking a fight, instead of a legitimate and valuable use of time spent.

**Comment by senlin** [comment]
> no pushback will be necessary

I fully agree!

**Comment by scottybo** [comment]
Hi @senlin @hlashbrooke - really interesting conversation happening here!

In terms of a plan, it will look something like this:

- Ask everyone who has volunteered to become a team member on the ClassicPress repo
- I'll learn more about each volunteer to understand their strengths, weaknesses and availability and based on this assign issues to them
- the volunteer can either respond to the issue saying they can't take it on or reply with a time frame for when they can complete the issue (if they decline the issue I'll assign it to the next best volunteer) 

I have a core WordPress developer advising me in the background on the technical practicalities of this fork (such as unit testing and automation of merges from the 4.9.8 trunk) - they're not happy with the direction WordPress is taking either. I'll have a much clearer plan in place in the next couple of days and I'll share it here for discussion.

As far as GPL goes, it's my biggest priority not to have any legal issues. I'm not a lawyer so I'll be very open to advice on this topic.

Lastly, I just want to say THANK YOU! Having you both here means a huge amount and any help you can offer is gratefully received.

**Comment by hlashbrooke** [comment]
That sounds like a solid start and a good way forward.

Just to clarify my own position - I'm not going to be getting involved in this fork (I believe in Gutenberg and I'd rather contribute to WordPress itself), but I'm glad you're going to be doing things the right way and with good intentions. Best of luck to you :)

**Comment by senlin** [comment]
@scottybo good plan, please keep me posted as I am very much looking forward to getting involved!

Cheers,
Pieter

**Comment by danieltj27** [comment]
I'd advise that this repo gets closed and opened a-new which is not a fork of the WordPress repo and then manually push a 4.9.8 version (so we don't have the official WordPress repo fork info and other meta carried over). Then from there do the editing. At the moment you also have all the baggage like old branches etc and much of the internals will need stripping out anyway so a 'GitHub fork' isn't the way to go here.

**Comment by scottybo** [comment]
Closing this issue for now as we've moved to a new repo - I agree that a fork can be messy, but at the same time it maintains the entire history which I think is more important
