### ISSUE TITLE
naming of the fork

### ISSUE THREAD

**Issue by senlin** [ClassicPress/ClassicPress_Deprecated#13]
Perhaps it is an idea to move away from the "Press" completely?

WordPress started as a fork from b2/cafelog. Nothing in its name suggests any of its origins. And that is a good thing as it became something completely different than its predecessor.

Also as the name ClassicPress [supposedly already is a theme](https://github.com/ClassicPress/ClassicPress/issues/11#issuecomment-415956807) on the Mojo marketplace, we can maybe come  up with something more original?

**Comment by scottybo** [comment]
If there's one thing I've learnt over my career in marketing, it's not to change the name of a brand unless there's a significant benefit in doing that.

The momentum behind ClassicPress is big and growing right now, and I'd be very hesitant to change the name just as its becoming one of the most talked about WordPress topics since Gutenberg!

**Comment by senlin** [comment]
Hi Scott, ok fair enough.
