### ISSUE TITLE
How will ClassicPress compete in the future?

### ISSUE THREAD

**Issue by danieltj27** [ClassicPress/ClassicPress_Deprecated#4]
Hi, interesting project and it'll be good to see where it heads.

I've got a few questions though that puts doubt in my mind where forking is concerned as it's clearly not a sustainable thing if not done the right way so I wanted a bit more information.

 1. How will ClassicPress cope when Gutenberg takes over more and more of the WordPress experience? You mentioned that non-Gutenberg features will be added as well as security enhancements, but I don't see how it'll work when Gutenberg (pretty much) rewrites the whole of wp-admin. At that point ClassicPress will have to be a different piece of software; a new CMS.

 2. How are you going to deal with plugin and theme compatibility going forward? I noticed in issue #2 that you need to get API endpoints setup, but updates will still need to come from WordPress.org in order to ensure every plugin/theme in the directories are still available for updates.

 3. How will you manage what goes in and what doesn't? Feature-wise; Gutenberg is going to rock the software ship quite a bit. Not everything will need/be able to go in. Especially for security issues being patched, a very close eye will need to be kept on commits and I don't see how it's possible to keep up with constant changes in SVN all the time. Falling behind a version or two seems likely in this case.

 4. What is your infrastructure like? If ClassicPress takes off, how will you meet the demand of site resources and ensure commitment from dedicated developers/designers/supporters etc? It'll be a massive undertaking to have volunteers to maintain the project. How do you see yourself recruiting these people?

Overall I do like the idea and I'm not a big fan of Gutenberg, it must be said. I'm just hesitant of the seer workload and difficult maintaining a parallel project will be. Apologies if you've answered these questions elsewhere. I've tried to keep up with the conversation as best as possible.

Best of luck 👍

**Comment by scottybo** [comment]
These are excellent questions, thank you for taking the time to note them down. I'll do my best to answer them!

1. You're correct, at some point in the future the divergence will be so great that ClassicPress will be its own entity. The way I see it _right now_ is that the focus will be on keeping security and bug fixes up to date and make sure any major developer functionality gets mirrored (rather than UI/UX functionality). Longer term, ClassicPress will be just that - a classic version of WordPress which will evolve as the community decides.

2. I guess this depends on what WordPress will allow. Perhaps they'll go nuclear and say we're not allowed to query their endpoints (which is their right to do). I guess this will then push us to create our own plugin/theme directory. No doubt this will be an adventure in and of itself. I'd probably suggest using Laravel as a base for that project.

3. It's a valid concern - people power is the answer right now. We need anyone and everyone who is willing and able to commit their time to jump in and make a stand.

4. I run [Holly Social](https://www.chooseholly.com) and we're going to cover the costs initially. Depending on how this grows we might need to start talking to hosting providers themselves to sponsor the project. As for recruitment - the good old fashioned way. Marketing the project and talking to people.

Yes, it's a big project - but nothing worthwhile in life is easy, and I firmly believe that WordPress is having its Digg moment right now. Perhaps ClassicPress will be the one that forks successfully, perhaps someone else will come along with a "better" fork. Either way, I think this is a pivotal moment and I've got to give it a shot.

**Comment by pcfreak30** [comment]
`I guess this depends on what WordPress will allow. Perhaps they'll go nuclear and say we're not allowed to query their endpoints (which is their right to do). I guess this will then push us to create our own plugin/theme directory. No doubt this will be an adventure in and of itself. I'd probably suggest using Laravel as a base for that project.`

Funny. I have the domain wprepo.org, been sitting on it as I have a todo list of pet projects/ideas to get to and it has been on the backburner for a while. But this split may be a catalyst for the idea which at the core is the iOS cydia (jailbreaking) for wordpress in having independent plugin/theme repos with a defined standard.

**Comment by scottybo** [comment]
@pcfreak30 very interesting - kind of like fdroid?

**Comment by pcfreak30** [comment]
Yes though the updater is already in core :)

**Comment by danieltj27** [comment]
> You're correct, at some point in the future the divergence will be so great that ClassicPress will be its own entity. The way I see it right now is that the focus will be on keeping security and bug fixes up to date and make sure any major developer functionality gets mirrored (rather than UI/UX functionality). Longer term, ClassicPress will be just that - a classic version of WordPress which will evolve as the community decides.

So in a sense, it'll be a little bit like _Old School RuneScape_ (that's the only thing I can compare it to considering the structure and direction etc). So it'll branch off at some point to become its own entity? At which point it'll probably no longer be able to be called a fork as it'll become too different to WordPress itself.

With that in mind, what are your thoughts on that point in the future? Is this a long term solution that you're prepared to spearhead? I just sense that with the sheer size of WordPress as it currently is, it'll be a monumental task of keeping it in sync so to speak with current WordPress. I'm curious how you'll manage the workload and ensure that CP gets the same updates as WP going forward It won't be easy.

> I guess this depends on what WordPress will allow. Perhaps they'll go nuclear and say we're not allowed to query their endpoints (which is their right to do). I guess this will then push us to create our own plugin/theme directory. No doubt this will be an adventure in and of itself. I'd probably suggest using Laravel as a base for that project.

This concerns me, simply because it would mean forcing a community of two halves where some plugins may work on either system, yet others might not. It would almost definitely require its own directory of themes and plugins I feel. The cross over what get to confusing, but we also run the risk of not having popular plugins available like Akismet, Yoast, ACF etc.

> It's a valid concern - people power is the answer right now. We need anyone and everyone who is willing and able to commit their time to jump in and make a stand.

How do you plan to advertise this? Judging on the somewhat small timeline before 5.0 and the end of August (which is when you've planned the first milestone), there'll be a lot that needs shouting about to make sure contributors come over. 

> I run Holly Social and we're going to cover the costs initially. Depending on how this grows we might need to start talking to hosting providers themselves to sponsor the project. As for recruitment - the good old fashioned way. Marketing the project and talking to people.

That may be difficult to get hosts on board when they're so heavily invested in WordPress; I suspect there might be a need for financial support much earlier than expected, especially if things pick up quickly.

**Comment by scottybo** [comment]
Closed as repo has moved to https://github.com/ClassicPress/ClassicPress
